spring:
  application:
    name: payout

  datasource:
    url: jdbc:h2:mem:payoutdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  logging:
    level:
      org.springframework: INFO
      org.springdoc: DEBUG


  # Optional H2 console (good for dev/debug)
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

